const RACES = [
  "Human", "High Elf", "Wood Elf", "Drow", "Hill Dwarf", "Mountain Dwarf",
  "Lightfoot Halfling", "Stout Halfling", "Rock Gnome", "Forest Gnome",
  "Half-Elf", "Half-Orc", "Tiefling", "Dragonborn", "Aasimar", "Goliath",
  "Tabaxi", "Kenku", "Lizardfolk", "Tortle", "Firbolg", "Yuan-ti",
];

const WEAPONS = [
  "longsword", "shortsword", "dagger (hidden)", "two daggers",
  "handaxe", "battleaxe", "greataxe", "warhammer", "maul",
  "spear", "quarterstaff", "club", "mace",
  "shortbow", "longbow", "crossbow (light)", "crossbow (heavy)",
  "rapier", "whip", "net and trident",
  "unarmed — no weapon", "unarmed — fighting gloves",
  "improvised — whatever's nearby", "a strange weapon, hard to name",
];

const ARMOR = [
  "no armor at all", "travelling clothes, no protection",
  "worn leather, cracked at the joints", "studded leather, well-maintained",
  "a single pauldron, mismatched gear", "piecemeal armor, cobbled together",
  "hide armor, rough-stitched", "chain shirt, no other protection",
  "scale mail, dented", "breastplate only",
  "full chain mail", "half-plate",
  "a shield but no armor", "heavy cloak, concealing something underneath",
  "robes — scholarly or religious", "ceremonial armor, not built for fighting",
];

const SECRETS = [
  "in search of something they lost long ago",
  "carrying something dangerous they won't explain",
  "running from someone who's still looking",
  "owes a debt that can't be repaid in coin",
  "knows something about someone powerful — and knows to keep quiet",
  "not who they say they are",
  "was present when something terrible happened",
  "is being watched, and knows it",
  "made a promise they regret",
  "is dying, and hasn't told anyone",
  "was once someone important, and walked away from it",
  "has a second loyalty no one knows about",
  "is looking for a specific person",
  "did something unforgivable — and got away with it",
  "knows where something is buried",
  "was betrayed, and hasn't decided what to do about it",
  "has done this before — the last time didn't end well",
  "is keeping someone else's secret, not their own",
  "arrived just before something went wrong — make of that what you will",
  "has a price on their head in a place they're trying to get back to",
  "lost something here once and never really left",
  "is the only one who didn't run when they should have",
  "knows exactly what this place is — and came anyway",
  "hasn't slept properly in weeks",
  "is pretending not to recognize someone in the room",
  "swore an oath that now puts them at odds with everything they want",
];

const HOOKS = [
  "needs something moved without questions asked",
  "is looking for someone who doesn't want to be found",
  "has information worth more than they realize",
  "is the last person standing between something bad and everyone else",
  "is protecting someone at great personal cost",
  "wants revenge but lacks the means",
  "is trying to stop something before it's too late",
  "has made an enemy of exactly the wrong person",
  "is sitting on a secret that could change everything",
  "needs the party to do something they can't be seen doing themselves",
  "is the only one who knows the way",
  "is about to make a terrible decision and doesn't know it",
  "has already done something the party will care about — they just don't know yet",
  "is in the wrong place and knows far too much",
  "is being used by someone else and is starting to suspect it",
  "has outlived everyone who knew their real name",
  "is owed a favor by someone very dangerous — and is finally collecting",
  "came here for one reason and found something that changed everything",
  "is the only survivor, and doesn't know why",
  "has been hired by two different people for the same job",
  "knows this ends badly and is doing it anyway",
  "is waiting for someone who isn't coming",
  "recently walked away from something — and it followed them",
  "has a way in, but won't say how they know it",
  "is carrying a message they haven't read",
  "made a deal they thought was symbolic — it wasn't",
  "has been here before, under a different name",
  "is trying to undo something they set in motion years ago",
  "is the reason this problem exists, though they'd never say so",
  "trusts the party for reasons they haven't explained yet",
];

const GEMS = [
  "a bloodstone, deep red flecked with green",
  "a pale moonstone, faintly luminescent",
  "a rough-cut amethyst, thumb-sized",
  "a cluster of small garnets, still in matrix rock",
  "an obsidian disk, carved with a symbol",
  "a cracked sapphire, still valuable",
  "a topaz the color of old honey",
  "a piece of raw amber with something inside it",
  "a jade figurine, small enough to pocket",
  "a string of black pearls, seven total",
  "a fire opal, flickering even in still light",
  "a diamond chip, wrapped in velvet",
  "a carved onyx seal",
  "a smoky quartz pendant, chain broken",
];

const CONSUMABLES = [
  "Potion of Healing", "Potion of Healing", "Potion of Healing",
  "Potion of Greater Healing",
  "Potion of Invisibility", "Potion of Speed", "Potion of Fire Breath",
  "Potion of Water Breathing", "Potion of Resistance (fire)",
  "Potion of Resistance (cold)", "Potion of Climbing",
  "Potion of Heroism", "Oil of Slipperiness",
  "Scroll of Charm Person", "Scroll of Darkness",
  "Scroll of Hold Person", "Scroll of Misty Step",
  "Scroll of Thunderwave", "Scroll of Detect Magic",
  "Dust of Disappearance", "Antitoxin",
];

const MAGIC_A = [
  "+1 Weapon (type fits the enemy)", "+1 Shield", "+1 Ammunition (x10)",
  "Bag of Holding", "Cloak of Protection", "Eyes of the Eagle",
  "Periapt of Wound Closure", "Ring of Feather Falling",
  "Boots of Elvenkind", "Cloak of Elvenkind",
  "Hat of Disguise", "Slippers of Spider Climbing",
  "Wand of Magic Missiles", "Wand of Secrets", "Staff of the Adder",
  "Lantern of Revealing", "Headband of Intellect", "Gauntlets of Ogre Power",
];

const MAGIC_B = [
  "+2 Weapon (type fits the enemy)", "Cloak of Displacement",
  "Necklace of Fireballs", "Ring of Evasion", "Robe of Eyes",
  "Staff of Charming", "Staff of Healing", "Wand of Paralysis",
  "Flame Tongue", "Sun Blade", "Oathbow",
  "Nine Lives Stealer", "Mace of Terror", "Dwarven Thrower",
];

const MAGIC_C = [
  "+3 Weapon (type fits the enemy)", "Staff of Fire", "Staff of Frost",
  "Staff of Power", "Vorpal Sword", "Cloak of Invisibility",
  "Ring of Three Wishes", "Efreeti Bottle",
];

const INTEL = [
  "a hand-drawn map of a nearby location, exits marked",
  "a letter with orders — someone higher up is pulling strings",
  "a journal with recent entries, last one dated three days ago",
  "a list of names, some crossed out",
  "a crude sketch of the party — they were being watched",
  "a wax-sealed message, unread, addressed to someone in town",
  "a codebook — whatever cipher they're using, this cracks it",
  "a ledger of transactions, one column is people",
  "a symbol or insignia you don't recognize — but it's everywhere",
  "a torn page describing this location in detail — written before they arrived",
  "a password or passphrase, written on the inside of a wrist bracer",
  "a rough timeline of planned events — one is very soon",
  "a confession, unsigned, implicating someone the party knows",
  "a map with a location marked that doesn't appear on any other map",
];

const ENCOUNTER_TYPES=[
"Enemy fleeing — target is attempting escape",
"Hostage situation — aggression risks innocent lives",
"Rescue operation — someone is in immediate danger",
"Elevation problem — terrain height strongly favors one side",
"Neutralize key target — one enemy matters more than the others",
"Protect vulnerable target — something important must survive",
"Prevent escape — stop a target from getting away",
"Prevent objective completion — enemies are progressing toward something",
"Recover important object — securing an item matters most",
"Secure area — control of a location is the goal",
"Hold position — abandoning ground means failure",
"Delay advancing force — buy time rather than win outright",
"Break enemy formation — enemies gain strength by staying organized",
"Reach destination — getting somewhere matters more than fighting",
"Escape dangerous area — staying becomes increasingly deadly",
"Maintain stealth — discovery changes the situation",
"Split priorities — multiple urgent goals compete for attention",
"Enemy reinforcements imminent — time is against you",
"Cross hazardous terrain — environment itself is dangerous",
"Planar instability — reality behaves unpredictably",
"Reality distortion — things may not be what they appear",
"Environmental collapse — surroundings are actively breaking down",
"Competing factions present — not everyone shares goals",
"Unstable magic effects — magical effects behave strangely",
"Civilians caught nearby — collateral damage matters",
"Unknown threat emerges — encounter changes unexpectedly",
"Timed pressure — a consequence approaches quickly",
"Enemy fortification — enemies prepared the battlefield",
"Restricted movement — movement options are limited",
"Terrain advantage problem — enemies control superior ground",
];

const MOODS = [
  "slow dread — something is wrong but no one can name it yet",
  "false calm — too quiet, too still, everything waiting",
  "chaotic stumble — they walked into the middle of something already in progress",
  "tense standoff — everyone is armed and no one wants to move first",
  "negotiation on a knife's edge — words matter here, and everyone knows it",
  "overwhelming odds — the math is bad and they can see it",
  "something has already gone wrong — they're arriving too late",
  "eerie familiarity — this place or situation feels like something they've seen before",
  "fractured attention — multiple things demand response at once",
  "a single point of focus — everything narrows to one decision",
  "creeping realization — the pieces are coming together and none of them like where it's going",
  "controlled chaos — someone is clearly running this, they just can't tell who",
  "the calm before — everyone knows what's coming, no one says it",
  "an unexpected offer — someone here wants to make a deal",
  "misdirection — what they came for isn't what matters here",
  "isolation — help is not coming, and they feel it",
  "time pressure — the window is closing and they know it",
  "something watching — they're not the only ones observing this scene",
  "a test — whether they know it or not, they're being evaluated",
  "grief made physical — the cost of something past is visible here",
];

const THREATS = [
  "already there, waiting — they knew the party was coming",
  "arrives mid-scene, cutting off retreat",
  "never appears directly — only their influence is felt",
  "speaks first, through an intermediary",
  "is announced by what they've done to this place",
  "lets the party get comfortable, then arrives",
  "was someone in the room all along",
  "sends a warning — a single, deliberate act — before showing themselves",
  "appears at the worst possible moment, when the party is already compromised",
  "is heard before they're seen",
  "makes an offer before making a threat",
  "arrives in a form the party doesn't immediately recognize",
  "has already won something — the party just doesn't know it yet",
  "doesn't arrive — the party is brought to them",
  "is revealed by a betrayal",
  "enters without drama — the danger is in how calm they are",
  "is introduced by reputation first — an NPC's reaction before the party sees anything",
  "leaves evidence of their presence but doesn't appear at all this scene",
  "gives the party exactly one chance to walk away",
  "arrives as a consequence of something the party did earlier",
];

const TIER_WEIGHTS = ["low","low","medium","medium","medium","high","high","deadly"];

const TIERS = {
  low:    { countMin:2, countMax:6,  strongChance:0.10, complicationChance:0.20 },
  medium: { countMin:3, countMax:8,  strongChance:0.30, complicationChance:0.40 },
  high:   { countMin:3, countMax:10, strongChance:0.55, complicationChance:0.60 },
  deadly: { countMin:2, countMax:8,  strongChance:0.80, complicationChance:0.80 },
};

const STRONG_MIX = {
  low:    ["1 specialist, rest are grunts"],
  medium: ["1 specialist, rest are grunts","2 specialists, rest are grunts","1 elite, rest are grunts"],
  high:   ["1 elite + 1 specialist, rest are grunts","2 elites, rest are grunts","mostly specialists, 1 elite leading","1 very dangerous individual and a handful of grunts"],
  deadly: ["1 boss-tier enemy with grunt support","2 elites, no grunts — small and lethal","a single, very powerful enemy","1 boss + specialists — no weak links"],
};

const SPACING = [
  "all together, tight formation",
  "clustered in two groups with a gap between",
  "spread across the space with no clear center",
  "most together, one flanking position already taken",
  "one or two hanging back — ranged or support",
  "staggered — they'll arrive in waves, not all at once",
  "one is separated and exposed — if the party moves fast",
  "surrounding a central point — the party walks into the middle",
  "high ground already claimed by at least one",
  "split across two levels or chokepoints",
];

const COMPLICATIONS = [
  "someone here shouldn't be hurt — civilian, prisoner, hostage",
  "an objective matters more than the fight — something must be grabbed, stopped, or protected",
  "the environment is unstable — fire, flooding, collapsing, something breaking",
  "reinforcements are coming — the clock is running",
  "one enemy will run and bring more if they escape",
  "there's something in the room the enemies are also trying to reach",
  "one of the enemies wants to defect — but the others don't know yet",
  "the party is compromised coming in — low on resources, separated, or surprised",
  "the goal is capture, not kill — on one side or both",
  "a third party arrives mid-fight with their own agenda",
  "visibility is bad — darkness, smoke, fog, chaos",
  "something here shouldn't be damaged — fragile, sacred, or dangerous if broken",
  "one enemy is bait — the real threat is elsewhere",
  "the enemies have already prepared — traps, barricades, chokepoints",
  "the fight draws attention — noise or duration matters",
];

const FLAVORS = [
  "a slime, inexplicably trapped in a jar — it seems fine with this",
  "a baby dragon, very small, very lost, extremely confident about it",
  "a book with a drawing inside that is yelling at the party",
  "a sword stuck in the floor. no stone. no plinth. just the floor. it won't budge",
  "a cat that has clearly been here for years and belongs to no one",
  "a mirror that shows the room as it was, not as it is",
  "a small door at ankle height, locked, with light coming from under it",
  "a chair facing the wall with fresh food on the table next to it",
  "a bird in a cage, door open, bird will not leave",
  "a painting whose subject has moved since whoever hung it last saw it",
  "a circle of salt, unbroken, with nothing inside it",
  "a severed hand, neatly placed on a shelf, pointing at something",
  "a jar of teeth, labeled in a language no one speaks",
  "a child's shoe, single, in the middle of the room",
  "a note that reads only: 'don't'",
  "a fire that burns without fuel and gives off no heat",
  "a very old man asleep in a chair who cannot be woken",
  "a dog that understands everything being said but is pretending not to",
  "a clock that runs backwards and is otherwise perfectly normal",
  "a pile of coins arranged into a face",
  "a message scratched into the floor, partially obscured: 'it already kn—'",
  "a perfectly made bed in a place where no one should be sleeping",
  "a wanted poster for someone who looks exactly like one of the party",
  "a music box playing a song one of the party members knows from childhood",
  "a set of manacles with no key and no prisoner, still warm",
  "a map of this exact location, drawn from above, marked with an X where the party is standing",
  "a skull with a candle in it, still lit, no wax dripped",
  "a letter addressed to one of the party members, sealed, already old",
  "a dagger pinning a note to the wall: 'you're welcome'",
  "a tiny campfire, recently used, sized for something much smaller than a person",
  "a throne made of weapons, none of them the same",
  "a window that looks out on a place that isn't outside",
  "a locked box with breathing holes",
  "a child's drawing of the party, pinned to the wall — it's accurate",
  "a barrel of something that smells incredible but looks wrong",
  "a ghost doing chores, completely ignoring the party",
  "a rope hanging from the ceiling that goes up further than it should",
  "a pile of identical rings, hundreds of them",
  "a single lit candle surrounded by dozens of melted ones — it's been burning a long time",
  "an empty bird's nest containing one coin, one tooth, one button",
  "a trapdoor with no ladder and no bottom visible",
  "a helmet with something growing inside it",
  "a very formal place setting for one, food still hot",
  "a book of names, last entry recent, last entry is someone the party knows",
];

console.log("Encounter types loaded:", ENCOUNTER_TYPES);
